language: ruby

rvm:
  - ruby-head
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-head
  - jruby-9
  - jruby-19mode
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
